version: "3.9"
services:
  robo-gym-environment-jupyter:
    build: 
      context: .
      dockerfile: jupyter.Dockerfile
    # image: moyash/robo-gym-env-jupyter:cuberoom
    container_name: environment
    networks: 
      - robogym-network
    ports:
      - "6060:8888"
    user: root
    command: jupyter lab --allow-root --LabApp.token='' --ip='0.0.0.0' --no-browser
  robo-gym-robot-server:
    image: moyash/robo-gym-rs:cuberoom
    container_name: robot-server
    networks: 
      - robogym-network
    # environment:
    #   - DISPLAY=192.168.1.7:0
    command: bash -c "source /robogym_ws/devel/setup.bash && start-server-manager && tail -f /dev/null"
        
networks: 
  robogym-network:
    driver: bridge
